### ISSUE TITLE
The REPL experience is not polished.

### ISSUE THREAD

**Issue by littleredcomputer** [littleredcomputer/math#2]
1) When running with `lein repl`, simplification and prettyprinting are not applied to expression results automatically. (One can wrap expressions with `(print-expression)` as a workaround.)

2) When running using `lein run -m net.littleredcomputer.math.repl`, the printing is right, but the command line editing keys do not work.

(We should let `lein repl` do the work. The trick is to figure out how to intercept values before printing. This looks like a job for nrepl middleware, something I know nothing about, so I'll learn something new. If that pans out, I'll get rid of the repl class).

**Comment by alexgian** [comment]
That would be great if it can be done, although - personally - I wouldn't prioritise it highly.  There exist effective workarounds.
I'd give priority to issue #1 (printing MultiFns), but again that's just from my point of view.

**Comment by alexgian** [comment]
You are probably aware of this but another difference between `lein repl` and  `lein run -m net.littleredcomputer.math.repl` is that the first will close using `(exit)` where second needs Ctl+D.
