### ISSUE TITLE
Generic functions don't print nicely.

### ISSUE THREAD

**Issue by littleredcomputer** [littleredcomputer/math#3]
Evaluating something like (up sin cos) produces

(up
 #object[clojure.lang.MultiFn 0x2c8c16c0 "clojure.lang.MultiFn@2c8c16c0"]
 #object[clojure.lang.MultiFn 0x329bad59 "clojure.lang.MultiFn@329bad59"])

when printed. It's correct from Clojure's point of view, but ugly. Perhaps the standard generic functions could be tagged with metadata that would suggest a prettier print format that (print-expression) could then substitute.

**Comment by alexgian** [comment]
You're still ahead of MIT-Scheme scmutils.
There, `(up sin cos tan)` yields `(up (??? arg) (??? arg) g:tan)` !!
