### ISSUE TITLE
Generic functions - further improvement to formatting

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/math#6]
MIT ScmUtils prints as follows when a (symbolic) derivative of a function is computed:
```
> (D sin)
#| a-euclidean-derivative |#
```
Further, when a function is defined or composed, we have the slightly off-putting
```
> (define (slope x y) (/ y x))
slope
> slope
#| (??? arg) |#
> (compose sin cos)
#| (??? arg) |#
```
I think `(??? arg)` is just its way of saying "unknown function", but I've seen people who think they've made an error on seeing that.

Here, we have:
```
 > (defn slope [x y] (/ y x))
slope
 > slope
#object[net.littleredcomputer.math.env$slope 0x4a2b11c0 "net.littleredcomputer.math.env$slope@4a2b11c0"]
```
Could the formatter make this say "slope"?  its already in the string.
```
> (compose sin cos)
#object[clojure.lang.AFunction$1 0xee78f7b "clojure.lang.AFunction$1@ee78f7b"]
> (D (compose sin cos))
#object[clojure.lang.AFunction$1 0x1d03869a "clojure.lang.AFunction$1@1d03869a"]
```
Could the formatter say "A generated/composed function" or whatever?
I don't think the system can distinguish between the two cases (derivative or plain) like ScmUtils can?  Can it?  Even if not, something pretty in the output would be nice.

**Comment by littleredcomputer** [comment]
I'm going to let this one stew for a bit. In both my case and the real scmutils, the printing happens at the language layer (i.e. it is MIT Scheme and Clojure that are choosing these representations and not GJS). I think that MIT Scheme expends a little more effort to make function objects pretty to look at, while Clojure is trying to help by revealing the package and name of the generated Java inner class.

Different audiences will appreciate different things here. I don't disagree with you that the printed representation is ugly. But the result of an expression like (compose sin cos) is an unapplied function object: something the casual user is not likely to see. By contrast, the value of (def sc (compose sin cos)) is a Var. Clojure prints Vars just like you would expect: just the name. Vars also contain metadata like the filename/line number where they were defined, and the docstring. Clojure has made its choice here and I think we should stick with it: note that the value of an expression like (fn [x] (+ x 1)) is just as ugly as (compose sin cos), and for the same reason. Clearly we have no right to tamper with the printed representation of the former, so I'm just about convinced we should leave the latter alone too, even though you are right to point out that there is enough ambient information around to do a prettier job.

**Comment by alexgian** [comment]
Basically, I am aware of the points you make and agree, so with very minor reservations I am closing it for now.
