### ISSUE TITLE
Exponentation not defined on Complex

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/math#8]
(def pi (* 2 (asin 1)))   ;; do we have any pre-defined constants, BTW? couldn't see any.
(def e (exp 1))
(def i (complex 0 1))
(expt e (* i pi))

IllegalArgumentException No method in multimethod 'expt' for dispatch value: [java.lang.Double :net.littleredcomputer.math.complex/complex] clojure.lang.MultiFn.getFn (MultiFn.java:156)

**Comment by littleredcomputer** [comment]
These seem to work now: give it a pull.
For constants, Java gives us Math/PI and Math/E.

[net.littleredcomputer.math.env] > (expt Math/E (* (complex 0 1) Math/PI))
(complex -1.0 1.2246467991473532E-16)

**Comment by alexgian** [comment]
Seems fine.
