### ISSUE TITLE
Composition of operators

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/math#9]
Scmutils defines the product of operators (D, partial[pd in clojure])  as their compositon.
This has been correctly implemented by the "expt" function.  So,
```
> (defn ff[x y z] (+ (* x x y)(*y y z)(* z z x))) => ff
> (((expt D 2) ff)'x 'y 'z)
(down
 (down (* 2 y) (* 2 x) (* 2 z))
 (down (* 2 x) (* 2 z) (* 2 y))
 (down (* 2 z) (* 2 y) (* 2 x)))
```
great, so far - pd is also OK:
``` 
> (((expt (pd 0) 2) ff)'x 'y 'z)
(* 2 y)
```
However, it is not possible to use "*", 
```
> (((* D D) ff)'x 'y 'z)
ArityException Wrong number of args (3) passed to: operator/mul/fn--2789/fn--2790  clojure.lang.AFn.throwArity (AFn.java:429)
```
or even "compose":
```
(((compose D D) ff)'x 'y 'z)
AbstractMethodError net.littleredcomputer.math.operator.Operator.arity()Ljava/lang/Object;  net.littleredcomputer.math.function/compose (function.clj:285)
```
While this is not really a problem for "D", since all the uses are equivalent, it does cause problems with "pd".   Suppose I need to find ∂²f/∂x∂y
```
(((compose (pd 0)(pd 1)) ff) 'x 'y 'z)
AbstractMethodError net.littleredcomputer.math.operator.Operator.arity()Ljava/lang/Object;  net.littleredcomputer.math.function/compose (function.clj:285)
```
IOW, in the example above, using ```((expt (pd [0|1|2]) 2) ff)``` I could only compute ∂²ff/∂x², ∂²ff/∂y² or ∂²ff/∂z²  and not ∂²ff/∂y∂z or whatever, never mind ∂³ff/∂x∂y∂z.  We need to be able to combine operators using "*" or "compose", as in MIT-Scheme.  

I won't even mention application of **vector operators** as dot-products, cross-products, etc. yet,  I'm trying some simplistic implementations of vector calculus of my own.  I know that Scmutils does have its own vector calculus routines, they seem very generalised (based on Spivak, I think).  I do not know if grad, div and curl are implemented as composable vector operators there, but I would be surprised if they're not*. I'd want to be sure everything works on a basic level first, before having a stab at that!

----
PS
\* They're not. I was surprised.

**Comment by alexgian** [comment]
Further, even expt seems to have problems with D, at higher levels:
```
> (defn fff [x y z] (+ (* x x y)(* y y y z)(* z z z z x)))   => fff
> > (((expt D 2) fff)'x 'y 'z)
(down
 (down (* 2 y) (* 2 x) (* 4 (expt z 3)))
 (down (* 2 x) (* 6 y z) (* 3 (expt y 2)))
 (down (* 4 (expt z 3)) (* 3 (expt y 2)) (* 12 x (expt z 2))))
```
but
```
(((expt D 3) fff)'x 'y 'z)

AbstractMethodError net.littleredcomputer.math.calculus.derivative.Differential.freeze()Ljava/lang/Object;  net.littleredcomputer.math.simplify/eval2708/fn--2709 (simplify.clj:214)
```
Should have been:
```
(down
 (down (down 0 2 0) (down 2 0 0) (down 0 0 (* 12 (expt z 2))))
 (down (down 2 0 0) (down 0 (* 6 z) (* 6 y)) (down 0 (* 6 y) 0))
 (down (down 0 0 (* 12 (expt z 2)))
       (down 0 (* 6 y) 0)
       (down (* 12 (expt z 2)) 0 (* 24 x z))))
```

**Comment by littleredcomputer** [comment]
Your earlier email about operators got me to thinking and I noticed some bugs in there. 
The main parts of this bug are fixed, here in the lab, except for the case of "fff", which as you point out is odd.

**Comment by alexgian** [comment]
I have managed to isolate the bug in "fff" reproducibly to *any8 3rd order derivative where one of the function parameters appears 4 times in the function body:
'''
> (defn f4[x] (* x x x x))
> (((expt D 3) f4) 2)

AbstractMethodError net.littleredcomputer.math.calculus.derivative.Differential.freeze()Ljava/lang/Object;  net.littleredcomputer.math.simplify/eval2708/fn--2709 (simplify.clj:214)
```

**Comment by alexgian** [comment]
Note that it will **not** present this problem if you define f4 as an exponent.
```
> (defn f4[x] (expt x 4))
> (((expt D 3) f4) 'x)
(* 24 x)
```

**Comment by alexgian** [comment]
Interestingly enough, check this out.  Hope it provides some hint
```
> (defn f4[x] (+ (* x x) (* x x)))
f4
>  (((expt D 3) f4) 'x)
0
> (defn f4[x] (* (* x x) (* x x)))
f4
>  (((expt D 3) f4) 'x)

AbstractMethodError net.littleredcomputer.math.calculus.derivative.Differential.freeze()Ljava/lang/Object;  net.littleredcomputer.math.simplify/eval2708/fn--2709 (simplify.clj:214)
> 
```
Seems it's not the actual number of instances of the variable appearing in the function body, but the fact that x is multiplied by itself 4 times.   Funny, that, since (expt x 4) works fine...

**Comment by alexgian** [comment]
Ooops
```
[net.littleredcomputer.math.env] > (defn f4[x] (+ (* x x x) (* x x x)))
f4
[net.littleredcomputer.math.env] >  (((expt D 3) f4) 'x)
4
```
